Vagrant.configure("2") do |config|

    config.vm.define :nodo1 do |nodo1|
      nodo1.vm.box = "debian/bookworm64"
      nodo1.vm.hostname = "nodo1"
      nodo1.vm.synced_folder ".", "/vagrant", disabled: true
      nodo1.vm.network :private_network,
        :libvirt__network_name => "red_aislada",
        :type => "dhcp",
        :libvirt__network_address => '192.168.123.0',
        :libvirt__netmask => '255.255.255.0',
        :libvirt__forward_mode => "none"
    end
    config.vm.define :nodo2 do |nodo2|
      nodo2.vm.box = "generic/ubuntu2204"
      nodo2.vm.hostname = "nodo2"
      nodo2.vm.synced_folder ".", "/vagrant", disabled: true
      nodo2.vm.network :private_network,
        :libvirt__network_name => "red_aislada",
        :type => "dhcp",
        :libvirt__network_address => '192.168.123.0',
        :libvirt__netmask => '255.255.255.0',
        :libvirt__forward_mode => "none"
    end
  end
