- hosts: all
  gather_facts: yes
  become: true
  tasks:
      # Actualizamos paquetes
    - name: Actualizamos el sistema
      apt: update_cache=yes upgrade=yes
      # Instalar paquetes
    - name: "Instalar paquetes con apt"
      apt: 
        name:
          - apache2
          - git
      # Copia un fichero a la máquina remota
    - name: "Copiar fichero a la máquina remota"
      copy: 
        src: files/foo.conf
        dest: foo.conf
        owner: root
        group: root
        mode: '0644'

      # Copia un template a un fichero
    - name: "Copiar un tamplate a un fichero de la máquina remota"
      template: 
        src: template/index.j2
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: 0644
    
