Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"
    config.vm.hostname="prueba"
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.network :private_network,
        :type => "dhcp",
        :libvirt__network_name => 'red_nat_vagrant',
        :libvirt__network_address => '192.168.200.0',
        :libvirt__netmask => '255.255.255.0'
        #:libvirt__host_ip => '192.168.200.1',
        #:libvirt__dhcp_start => '192.168.200.2',
        #:libvirt__dhcp_stop => '192.168.200.254',
        #use_dhcp_assigned_default_route: true
end
