Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"
    config.vm.hostname="prueba"
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.network :private_network,
        :libvirt__network_name => 'red_nat_sin_dhcp_vagrant',
        :libvirt__dhcp_enabled => false,
        :ip => "192.168.200.100"
end
